"""Add Review Model

Revision ID: b96f8fb52c4b
Revises: a4b27339a019
Create Date: 2023-12-08 08:42:37.174232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96f8fb52c4b'
down_revision = 'a4b27339a019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
